openapi: 3.0.1
info:
  title: Demo63 API
  description: API for managing facturas and clientes.
  version: 1.0.0
servers:
  - url: http://localhost:8080/demo63/rs/

paths:
  /facturas:
    post:
      summary: Crear una nueva factura
      requestBody:
        description: Factura a crear
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Factura'
      responses:
        '201':
          description: Factura creada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
    put:
      summary: Actualizar una factura existente
      requestBody:
        description: Factura a actualizar
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Factura'
      responses:
        '200':
          description: Factura actualizada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Factura'
        '404':
          description: Factura no encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
    delete:
      summary: Borrar una factura
      parameters:
        - in: query
          name: id
          schema:
            type: integer
          required: true
          description: ID de la factura a borrar
      responses:
        '201':
          description: Factura borrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        '404':
          description: Factura no encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'

  /facturas/list:
    get:
      summary: Obtener lista de facturas
      responses:
        '200':
          description: Lista de facturas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Factura'
        '404':
          description: No se registran facturas
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'

  /clientes:
    post:
      summary: Crear un nuevo cliente
      requestBody:
        description: Cliente a crear
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cliente'
      responses:
        '201':
          description: Cliente creado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
    put:
      summary: Actualizar un cliente existente
      requestBody:
        description: Cliente a actualizar
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cliente'
      responses:
        '200':
          description: Cliente actualizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cliente'
        '404':
          description: Cliente no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
    delete:
      summary: Borrar un cliente
      parameters:
        - in: query
          name: id
          schema:
            type: integer
          required: true
          description: ID del cliente a borrar
      responses:
        '201':
          description: Cliente borrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        '404':
          description: Cliente no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'

  /clientes/:
    get:
      summary: Obtener un cliente por cédula o nombre
      parameters:
        - in: query
          name: dni
          schema:
            type: string
          required: true
          description: DNI del cliente
        - in: query
          name: nombre
          schema:
            type: string
          required: true
          description: Nombre del cliente
      responses:
        '200':
          description: Cliente encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cliente'
        '404':
          description: Cliente no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'

  /clientes/{dni}/{nombre}:
    get:
      summary: Obtener un cliente por cédula y nombre
      parameters:
        - in: path
          name: dni
          schema:
            type: string
          required: true
          description: DNI del cliente
        - in: path
          name: nombre
          schema:
            type: string
          required: true
          description: Nombre del cliente
      responses:
        '200':
          description: Cliente encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cliente'
        '404':
          description: Cliente no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'

  /clientes/list:
    get:
      summary: Obtener lista de clientes
      responses:
        '200':
          description: Lista de clientes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Cliente'
        '404':
          description: No se registran clientes
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'

components:
  schemas:
    Factura:
      type: object
      properties:
        id:
          type: integer
        fecha:
          type: string
          format: date
        total:
          type: number
          format: float
        cliente:
          $ref: '#/components/schemas/Cliente'
    Cliente:
      type: object
      properties:
        id:
          type: integer
        nombre:
          type: string
        cedula:
          type: string
        direccion:
          type: string
        telefono:
          type: string
    ErrorMessage:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
