apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: demo63
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: villaltajose/front
        ports:
        - containerPort: 80