apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: demo63
spec:
  ports:
  - name: udp
    port: 6831
    protocol: UDP
    targetPort: 6831
  - name: web
    port: 16686
    protocol: TCP
    targetPort: 16686
  selector:
    app: jaeger
  type: LoadBalancer
